[tool.poetry]
name = "app"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
bolt = {git = "https://github.com/dropseed/bolt", branch = "main"}

[tool.poetry.group.dev.dependencies]
bolt-dev = {git = "https://github.com/dropseed/bolt", branch = "main", subdirectory = "bolt-dev"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
